name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        sudo apt install pipx
        pipx ensurepath
        pipx install poetry
        poetry install
    - name: Install browsers
      run: |
        playwright install --with-deps
    - name: Test with pytest
      run: |
        poetry run pytest
