name: Test Pytest configuration and launch
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

# Java dependencies
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: 21

# Python dependencies
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install poetry and dependencies
      run: |
        pipx ensurepath
        pipx install poetry
        poetry install
    - name: Install browsers
      run: poetry run playwright install --with-deps

    - name: Test with pytest
      run: poetry run pytest ./playwright_pytest/ -c ./pytest.ini

    - name: Get Allure history
      uses: actions/checkout@v4
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    - name: Build test report
      uses: simple-elf/allure-report-action@v1.7
      if: always()
      with:
        allure_results: allure-results
        allure_history: allure-history

    - name: Deploy report to Github Pages
      uses: peaceiris/actions-gh-pages@v4
      if: always()
      env:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: allure-history
