name: Test Pytest configuration and launch
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: 'poetry'
    - name: Install poetry and dependencies
      run: | 
        pipx ensurepath
        pipx install poetry
        poetry install
    - name: Install browsers
      run: |
        playwright install --with-deps
    - name: Test with pytest
      run: |
        poetry run pytest
