name: Regression manual launch
run-name: ${{ github.actor }} is launched regression tests 🚀
on:
  workflow_dispatch:
    inputs:
      browser:
        description: 'Log level'
        required: true
        default: 'chromium'
        type: choice
        options:
        - chromium
        - firefox
        - webkit
        - all
      environment:
        description: 'Environment to run tests against'
        required: true
        default: 'test'
        type: choice
        options:
          - dev
          - test
          - stage
          - prod
      tags:
        description: 'Allure filter spec to run selected set of tests'
        required: false
        default: '--allure-label tag=API,UI'
        type: 'string'

permissions:
  contents: write

jobs:
  run:
    name: Build, execute tests and publish
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

# Build test project
# Java dependencies
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: 21

# Python dependencies
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install poetry and dependencies
      run: |
        pipx ensurepath
        pipx install poetry
        poetry install
    - name: Install browsers
      run: poetry run playwright install --with-deps

# Execute tests
    - name: Test in all browsers
      if: inputs.browser == 'all'
      run: poetry run pytest ./playwright_pytest/ -c ./pytest.manual.ini --env ${{ inputs.environment }} --browser chromium --browser firefox --browser webkit ${{ inputs.tags }}

    - name: Test in ${{ inputs.browser }}
      if: inputs.browser != 'all'
      run: poetry run pytest ./playwright_pytest/ -c ./pytest.manual.ini --env ${{ inputs.environment }} --browser ${{ inputs.browser }} ${{ inputs.tags }}

# Publish
    - name: Get Allure history
      uses: actions/checkout@v4
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    - name: Build test report
      uses: simple-elf/allure-report-action@v1.7
      if: always()
      with:
        allure_results: allure-results
        allure_history: allure-history

    - name: Deploy report to Github Pages
      uses: peaceiris/actions-gh-pages@v2
      if: always()
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: allure-history
